version: "3.9"

services:
  db:
    image: influxdb
    restart: always
    networks:
      - backend
      - frontend
    ports:
      - 8086:8086

volumes:
  influxdb_data:

networks:
  frontend:
  backend:
